name = "BackboneIdealization"
uuid = "c0a2461d-ad31-482d-b417-21333ed28a5d"
authors = ["Anton Oresten <antonoresten@gmail.com> and contributors"]
version = "0.0.1"

[deps]
Backboner = "9ac9c2a2-1cfe-46d3-b3fd-6fa470ea56a7"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ParameterSchedulers = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"

[weakdeps]
ProteinChains = "b8e8f2a5-48d3-44f1-ba0d-c71cb7726ff8"

[extensions]
ProteinChainsExt = "ProteinChains"

[compat]
Backboner = "0.12"
Flux = "0.16"
Optimisers = "0.4"
ParameterSchedulers = "0.4"
ProteinChains = "0.6.2"
julia = "1.10"

[extras]
ProteinChains = "b8e8f2a5-48d3-44f1-ba0d-c71cb7726ff8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ProteinChains"]
